[package]
name = "arma3-reflection"
version = "0.1.0"
authors = ["Fusselwurm <fusselwurm@gmail.com>"]
edition = "2021"

[lib]
crate-type=["cdylib"]

[dependencies]
arma-rs = { git = "https://github.com/BrettMayson/arma-rs", branch = "legacy"}
