name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 32bit libs
      run: sudo apt-get install gcc-multilib        
    - uses: actions/checkout@v2
    - name: make
      run: make
