name: compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get toolchain
        with:
          toolchain: stable
        uses: actions-rs/toolchain@v1
      - name: cargo build
        run: cd extension && cargo build --release
      - run: cp extension/target/release/libarma3_reflection.so reflection_x64.so
      - name: Upload build artifact x86
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: reflection_x64.so
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: get toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo build win64
        run: cd extension && cargo build --release
      - run: copy extension/target/release/arma3_reflection.dll reflection_x64.dll
      - name: Upload build artifact x64
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: reflection_x64.dll
  pack_mod:
    runs-on: ubuntu-latest
    name: build mod
    needs: ["windows", "linux"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: extension
      - name: copy compiled extensions into mod
        run: cp *.dll *.so ./mod
      - name: pack
        id: pack
        uses: gruppe-adler/action-release-with-hemtt@2.1.0
        with:
          cwd: ./mod
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.pack.outputs.zip_path }}
          name: mod
