name: Linux x86 build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: update apt index
      run: sudo apt-get update
    - name: 32bit libs
      run: sudo apt-get install gcc-multilib g++-multilib
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Upload build artifact x86
      uses: actions/upload-artifact@v2
      with:
        name: arma3-reflection.so
        path: reflection.so
