name: quality checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  qc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-unknown-linux-gnu
          components: rustfmt, clippy
      - run: pushd
      - name: Test
        run: cargo test
      - name: Check
        run: cargo check
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
      - run: popd
