name: quality checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  qc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-unknown-linux-gnu
          components: rustfmt, clippy
      - name: Install Tarpaulin
        run: sudo apt-get install libssl-dev pkg-config && cargo install cargo-tarpaulin
      - name: Test with Coverage
        run: cd extension && cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./extension/target/tarpaulin/
          fail_ci_if_error: true
