name: Windows win32/x64 builds
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1
    - uses: actions/checkout@v2      
    - name: Build solution Win32
      run: msbuild /p:Configuration=Release /p:Platform=Win32
    - name: Build solution x64
      run: msbuild /p:Configuration=Release /p:Platform=x64
    - name: Upload build artifact Win32
      uses: actions/upload-artifact@v2
      with:
        name: arma3-reflection-Win32
        path: arma3-reflection/bin/Release|Win32
    - name: Upload build artifact x64
      uses: actions/upload-artifact@v2
      with:
        name: arma3-reflection-x64
        path: arma3-reflection/bin/Release|x64
